sudo rm /usr/bin/nmap
sudo rm /usr/bin/ncat
sudo rm /usr/bin/amass
sudo rm /usr/bin/hydra
sudo rm /usr/bin/rustscan
sudo rm /usr/bin/ffuf
sudo rm /usr/bin/subfinder
sudo rm /usr/bin/httpx
sudo rm /usr/bin/nuclei
sudo rm /usr/bin/vaf
sudo rm /usr/bin/webanalyze
sudo rm /usr/bin/s3scanner
sudo rm /usr/bin/gau
sudo rm /usr/bin/qsreplace
